wandb_version: 1

dataset_idx:
  value: 4
gb_lr:
  value: 0.1
gb_n_estimators:
  value: 100
mlp_layers:
  value:
  - 64
mlp_lr:
  value: 0.01
mlp_max_iter:
  value: 400
model:
  value: RandomForest
rf_max_depth:
  value: 20
rf_n_estimators:
  value: 100
