wandb_version: 1

dataset_idx:
  value: 32
gb_lr:
  value: 0.2
gb_n_estimators:
  value: 300
mlp_layers:
  value:
  - 128
  - 64
mlp_lr:
  value: 0.001
mlp_max_iter:
  value: 200
model:
  value: MLP
rf_max_depth:
  value: 10
rf_n_estimators:
  value: 300
