wandb_version: 1

dataset_idx:
  value: 27
gb_lr:
  value: 0.05
gb_n_estimators:
  value: 100
mlp_layers:
  value:
  - 64
mlp_lr:
  value: 0.001
mlp_max_iter:
  value: 200
model:
  value: MLP
rf_max_depth:
  value: null
rf_n_estimators:
  value: 300
