wandb_version: 1

dataset_idx:
  value: 5
gb_lr:
  value: 0.1
gb_n_estimators:
  value: 100
mlp_layers:
  value:
  - 128
  - 64
mlp_lr:
  value: 0.01
mlp_max_iter:
  value: 200
model:
  value: MLP
rf_max_depth:
  value: 10
rf_n_estimators:
  value: 300
