name: research
channels:
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - pygraphviz
  - scikit-learn
  - pip:
    - optuna
    - optuna-integration