name: research
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - atk-1.0=2.36.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - cairo=1.16.0
  - certifi=2024.12.14
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.6.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - gobject-introspection=1.78.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libboost=1.82.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - librsvg=2.56.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - ninja=1.12.1
  - ninja-base=1.12.1
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.0.15
  - packaging=24.2
  - pandas=2.2.3
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.0.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - poppler=24.09.0
  - poppler-data=0.4.11
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pydot=1.4.2
  - pygments=2.15.1
  - pygraphviz=1.14
  - pyparsing=2.4.7
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.12.8
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - readline=8.2
  - scikit-learn=1.5.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - tzdata=2024b
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - alembic==1.14.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==24.3.0
      - babel==2.16.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorlog==6.9.0
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - jinja2==3.1.5
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - mako==1.3.8
      - markupsafe==3.0.2
      - mistune==3.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - optuna==4.1.0
      - optuna-integration==4.2.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - prometheus-client==0.21.1
      - protobuf==5.29.3
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - python-json-logger==3.2.1
      - pyyaml==6.0.2
      - referencing==0.36.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.3
      - send2trash==1.8.3
      - sentry-sdk==2.20.0
      - setproctitle==1.3.4
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.37
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - urllib3==2.3.0
      - wandb==0.19.4
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.13
      - yarg==0.1.9
