_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 5
            "12": 0.19.4
            "13": linux-x86_64
batch_size:
    value: 32
dropout_rate:
    value: 0.2
early_stopping_patience:
    value: 50
epochs:
    value: 1000
hidden_dim:
    value: 64
l2_strength:
    value: 0.001
learning_rate:
    value: 0.01
num_trees:
    value: 20
random_state:
    value: 42
regularize_trees:
    value: true
weight_decay:
    value: 0.0005
