_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.10
            "8":
                - 1
                - 5
            "12": 0.19.10
            "13": linux-x86_64
dataset_idx:
    value: 12
gb_lr:
    value: 0.1
gb_n_estimators:
    value: 300
mlp_layers:
    value:
        - 64
mlp_lr:
    value: 0.001
mlp_max_iter:
    value: 400
model:
    value: RandomForest
rf_max_depth:
    value: 10
rf_n_estimators:
    value: 100
